# run binary classifier
# "sign_classes" : ["WORK-OUT", "INFORM", "LOOK", "SHOW", "BOSS", "NICE.CLEAN", "DRESS.CLOTHES", "COLLECT", "FINGERSPELL", "FED-UP.FULL", "VACATION", "DECREASE", "GUITAR", "SHELF.FLOOR", "MACHINE", "DEVELOP", "SAME", "DRIP", "DEVIL.MISCHIEVOUS", "CUTE", "COME", "PAST", "CITY.COMMUNITY", "ADVISE.INFLUENCE", "FIRE.BURN", "ANSWER", "DISCUSS", "GET-TICKET", "AGAIN", "CHAT", "MAD", "BOWTIE", "EXCUSE", "FACE", "EMPHASIZE", "CAMP", "COPY", "BLAME", "WEEKEND", "BIG", "EXPERT", "DOCTOR", "DATE.DESSERT", "INJECT", "FIFTH", "RUN", "APPOINTMENT", "HAPPY", "MARRY", "DEPRESS", "SILLY", "GROUND", "GOLD.ns-CALIFORNIA", "DISAPPOINT", "REPLACE", "STAND-UP", "ART.DESIGN", "CANCEL.CRITICIZE", "AFRAID", "GO", "EAT", "WALK", "ISLAND.INTEREST", "IN", "GOVERNMENT", "COP", "DRINK", "INCLUDE.INVOLVE", "LIVE", "TOUGH"]

python stage2model.py config_dirs.json config760_binaryclassifier.json WORK-OUT

